### ISSUE TITLE
the code part is broken - wrong formatting

### ISSUE THREAD

**Issue by medarob** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#20]
Hi,

I noticed that the code part seems to be broken in the documention for the viewhelpers.
It's hard to read:
https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/Cycle.html

![grafik](https://user-images.githubusercontent.com/33951787/64601516-5df30c80-d3bd-11e9-96c7-5aa6e434ae14.png)

best regards

**Comment by DanielSiepmann** [comment]
All Examples within `typo3fluid/fluid` Namespace are broken. This is mentioned on startpage of the reference.

There is already an Pull Request to fix this for upcoming releases: https://github.com/TYPO3/Fluid/pull/436
For older versions then 9.5, I'll do that by hand in the future.

**Comment by medarob** [comment]
btw. this is a screenshot/link to the documentation for 9.5. It seems to work for the 8.7 documentation.

**Comment by DanielSiepmann** [comment]
https://docs.typo3.org/other/typo3/view-helper-reference/8.7/en-us/typo3fluid/fluid/2.5.5/Cycle.html IT does not. For some reason the redirect is different when switching the version, then selecting the ViewHelper within navigation.

It's broken at all known official places.

As mentioned before, there is already a PR for Fluid to fix this, which needs to be merged. Afterwards TYPO3 can update the dependency to Fluid and this will be fixed for 9.5.

Still we need to migrate the markup for older versions, as they are one time generated due to heavy complexity.

**Comment by DanielSiepmann** [comment]
Fixed rendering for 8.7 via #21, still needs to be deployed.

I'll close this one, as we are already on that task, and don't track the progress here as well.
