### ISSUE TITLE
f:widget: Describe how to use custom pagination template

### ISSUE THREAD

**Issue by remonator** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#28]
I was looking at how to override the default template for the pagination ViewHelper and found information only on external sites ([example](https://www.oliver-thiele.de/cms-typo3/widgets-template-pfade-anpassen/)).

The community would benefit if this information was included in the official documentation.

The file appears to be at `TYPO3CMS-Reference-ViewHelper/Documentation/typo3/fluid/9.5/Widget/Paginate.rst `

**Comment by sypets** [comment]
I agree, the community would benefit if this were documented and I think this information is currently missing. 

The change you are proposing sounds a little more extensive. I do not know if it makes sense to add it directly to the source code for the paginate widget description. Also, it is general information for widgets, not just for the paginate widget, right? Also, the information in the phpdoc block usually contains only a short description with a few small examples. 

Another option might be (for example) adding a new page in the [Fluid](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Fluid/Index.html) chapter in "TYPO3 Explained". You could call it something like "Working with widgets in Fluid". The Fluid chapter was created recently, I am also thinking about moving some more general Fluid stuff there from Extbase / Fluid book, so that might not be such a bad choice.

You are welcome to create a pull request. You can also join the TYPO3 Slack channel `#typo3-documentation` and ask for help: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/HowToGetHelp.html

-----

Apart from that: here is a short description how you could make the modification yourself. Again, I do not think it is the best idea to put it there, but you can try. 

This ViewHelper reference is automatically generated from the source code of:

* TYPO3 CMS (https://github.com/TYPO3/TYPO3.CMS)
* and TYPO3 Fluid (https://github.com/TYPO3/Fluid)

You can make direct changes to the source code, either by using

* Edit on GitHub: Use Pencil to edit (you will effectively create a fork and a PR just like when you use "Edit me on GitHub" for the docs: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Widget/PaginateViewHelper.php
* or Use the core contribution workflow, which means creating a patch and working locally with Git and then push to Gerrit, see https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/BugfixingAZ/Index.html

In the core: **You must create a patch for the master branch** (the latest version). This may then get backported to 10.4 and 9.5.

**Comment by sypets** [comment]
New issue was opened on forge: https://forge.typo3.org/issues/91857
