### ISSUE TITLE
Optimizing cObject documentation?

### ISSUE THREAD

**Issue by rowild** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#6]
This page: `https://docs.typo3.org/typo3cms/ViewHelperReference/typo3/fluid/latest/CObject.html` explains `currentValueKey` with `currentValueKey`, which does not provide too much insight...

Also, according to a Slack comment, a construct like this should also be possible:
```
<f:cObject typoscriptObjectPath="lib.someLibObject">{someValue}</f:cObject>
```
But it is not documented here.

I'd like to provide my own explanations - but unfortunately I have no clue what this `currentValueKey` is good for. Hopefully I can encourage somebody to provide some explanation and maybe 1 or 2 examples. I'd be happy to review!

**Comment by sypets** [comment]
@rowild, I transferred this issue to [ViewHelper reference issues](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/issues). 

Since you referred to the automatic ViewHelper reference, the place to make changes to the source is  directly in the TYPO3 core (for this ViewHelper, anyway). The comments in the source file are being used to generate this ViewHelper reference:

see https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php

Because of this, I will create an issue for the core in https://forge.typo3.org/projects/typo3cms-core/issues

Hope that is ok for you.

**Comment by sypets** [comment]
https://forge.typo3.org/issues/88187

**Comment by rowild** [comment]
Thanks a lot, @sypets !
