### ISSUE TITLE
f:translate contains bad example  - ordering is not explained

### ISSUE THREAD

**Issue by Padina42** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#84]
I could not change it directly.

Bad example:
===========
   {f:translate(key: 'someKey', arguments: {0: 'dog', 1: 'fox'}, default: 'default value')}

Value of key ``someKey`` in the current website language
with the given arguments (dog and fox) assigned for the specified
``%s`` conversions (:php:`sprintf()`) in the language file::

   <trans-unit id="someKey" resname="someKey">
       <source>Some text about a %s and a %s.</source>
   </trans-unit>

The output will be "Some text about a dog and a fox".

Better example
================
Bad example:
   {f:translate(key: 'someKey', arguments: {0: 'dog', 1: 'fox'}, default: 'default value')}

Value of key ``someKey`` in the current website language
with the given arguments (dog and fox) assigned for the specified
``%s`` or ordered ``%1$s`` conversions (:php:`sprintf()`) in the language file::

   <trans-unit id="someKey" resname="someKey">
       <source>Some text about a %2$s being smaller than a %1$s.</source>
   </trans-unit>

The output will be "Some text about a fox being smaller than a dog".

**Comment by garvinhicking** [comment]
The ViewHelper docs are actually part of the fluid repository, which is why you probably couldn't easily create a PR for it.

Good auggestion to enhance this.
Personally I wouldn't change the example to be more complicated, but rather adjust the sentence that points to sprintf, and state something like: "You can also use placeholders for ordering arguments loke %1$s or other formatting like %d and %f, as outlined in the PHP documentation for sprintf (link)"?

Would you like to create a PR/issue in the repo https://github.com/TYPO3/Fluid or should I?

**Comment by garvinhicking** [comment]
Created a Forge issue and Gerritt patch (it's in the core of course, not the external typo3/fluid package):

https://review.typo3.org/c/Packages/TYPO3.CMS/+/84183
https://forge.typo3.org/issues/103808

Closing issue here.
