### ISSUE TITLE
Documentation missing version information

### ISSUE THREAD

**Issue by in-session** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#90]
According to the documentation, this should already be possible from 12.4., but that is not the case. It is not yet possible under 12.4.13. It would make sense to document this a little more precisely, stating which is available from which version.

https://docs.typo3.org/other/typo3/view-helper-reference/12.4/en-us/Global/Replace.html

**Comment by garvinhicking** [comment]
This viewhelper is part of the recent 12.4 release due to the fluid dependency that has been updated to 2.15.0 with TYPO3 12.4.22

We must keep the documentation in line with the recent patch levels - while we can document changes in major version, we must assume that every user of a v12 version is always using the most recent patch level.

I hope that explains the situation for you and it's ok to close the issue! Thanks for taking the time to report this. :-)
